spring:
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    consumer:
      fetch-min-size: 100

logging:
  level:
    root: info
    org.springframework.transaction: trace
    org.springframework.kafka: trace
